version: "3.9"
services:
  mysql-database:
    image: mysql-database
    build:
      context: ../
      dockerfile: ./docker/sql-database.Dockerfile
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - ../mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ../redis_data:/data
    networks:
      - backend

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - backend
    
  backend:
    image: taller-grado-backend
    build:
      context: ../
      dockerfile: dev.Dockerfile
    depends_on:
      - "mysql-database"
    volumes:
      - ../:/usr/src/app
    ports:
      - 3003:3003
    networks:
      - backend
      - frontend

networks:
  backend:
    name: backend
  frontend:
    name: frontend
