FROM mysql:5.7 AS DATABASE

#COPY CREATE DATA TO CONTAINER
#ADD /sql/model-create.sql /docker-entrypoint-initdb.d

#SETTING UP DATABASE INFORMATION
ENV MYSQL_ROOT_PASSWORD=abc123
ENV MYSQL_DATABASE=taller
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=abc123
