name: build-action
on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  deployment-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing the dependencies 
        run: npm install
      - name: Linting all the software
        run: npm run lint
